// ============================================================
// src/planning/plan-validator.test.ts — T14 unit tests
// ============================================================

import { describe, it, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import type {
  AgentBelief,
  IBeliefStore,
  ParcelBelief,
  Plan,
  PlanStep,
  Position,
  SelfBelief,
} from '../types.js';
import { PlanValidator } from './plan-validator.js';
import { BfsPlanner } from './bfs-planner.js';
import { BeliefMapImpl } from '../beliefs/belief-map.js';
import {
  FIXTURE_MAP_TILES,
  FIXTURE_MAP_WIDTH,
  FIXTURE_MAP_HEIGHT,
  FIXTURE_DELIVERY_ZONES,
} from '../testing/fixtures.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const fixtureMap = new BeliefMapImpl(FIXTURE_MAP_TILES, FIXTURE_MAP_WIDTH, FIXTURE_MAP_HEIGHT);

function makeParcel(id: string, pos: Position, carriedBy: string | null = null): ParcelBelief {
  return {
    id,
    position: pos,
    carriedBy,
    reward: 10,
    estimatedReward: 10,
    lastSeen: Date.now(),
    confidence: 1,
    decayRatePerMs: 0,
  };
}

function makeAgent(pos: Position, confidence = 1.0): AgentBelief {
  return {
    id: `agent-${pos.x}-${pos.y}`,
    name: 'enemy',
    position: pos,
    score: 0,
    lastSeen: Date.now(),
    confidence,
    heading: null,
    isAlly: false,
  };
}

function mockBeliefs(
  parcels: ReadonlyArray<ParcelBelief>,
  selfPos: Position,
  agents: ReadonlyArray<AgentBelief> = [],
): IBeliefStore {
  const zones = FIXTURE_DELIVERY_ZONES as Position[];

  return {
    updateSelf: () => {},
    updateParcels: () => {},
    updateAgents: () => {},
    updateCrates: () => {},
    mergeRemoteBelief: () => {},
    getSelf: () => ({
      id: 'agent-self',
      name: 'TestAgent',
      position: selfPos,
      score: 0,
      penalty: 0,
      carriedParcels: [],
    } satisfies SelfBelief),
    getParcelBeliefs: () => parcels,
    getAgentBeliefs: () => agents,
    getMap: () => fixtureMap,
    getNearestDeliveryZone: () => zones[0]!,
    getReachableParcels: () => parcels.filter(p => p.carriedBy === null),
    getCrateObstacles: () => [],
    getCrateBeliefs: () => new Map(),
    getCratePositionSet: () => new Set(),
    toSnapshot: () => ({
      agentId: 'agent-self',
      timestamp: Date.now(),
      selfPosition: selfPos,
      parcels: [],
      agents: [],
    }),
    getCapacity: () => Infinity,
    getExploreTarget: () => null,
    removeParcel: () => {},
    clearDeliveredParcels: () => {},
    markParcelCarried: () => {},
    onUpdate: () => {},
  };
}

/** Build a minimal valid Plan from explicit steps for testing. */
function makePlan(steps: PlanStep[]): Plan {
  return {
    id: 'test-plan',
    intentionId: '',
    steps,
    estimatedReward: 10,
    createdAt: Date.now(),
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('PlanValidator', () => {
  let validator: PlanValidator;

  beforeEach(() => { validator = new PlanValidator(); });

  // -------------------------------------------------------------------------
  // Happy path — BfsPlanner-generated plan
  // -------------------------------------------------------------------------

  it('accepts a plan generated by BfsPlanner', async () => {
    // Agent at (0,1), parcel at (0,5), delivery at (0,0)
    const startPos: Position = { x: 0, y: 1 };
    const parcelPos: Position = { x: 0, y: 5 };
    const deliveryPos: Position = { x: 0, y: 0 };

    const planner = new BfsPlanner();
    const result = await planner.plan({
      currentPosition: startPos,
      carriedParcels: [],
      targetParcels: [makeParcel('p1', parcelPos)],
      deliveryZones: [deliveryPos],
      beliefMap: fixtureMap,
    });
    assert.ok(result.success);

    const beliefs = mockBeliefs([makeParcel('p1', parcelPos)], startPos);
    const vr = validator.validate(result.plan!, beliefs);

    assert.ok(vr.valid, vr.reason);
    assert.equal(vr.reason, undefined);
  });

  it('empty plan is valid', () => {
    const beliefs = mockBeliefs([], { x: 4, y: 4 });
    const vr = validator.validate(makePlan([]), beliefs);
    assert.ok(vr.valid);
  });

  // -------------------------------------------------------------------------
  // (1) Target parcel no longer exists
  // -------------------------------------------------------------------------

  it('fails when target parcel is gone from beliefs', () => {
    const parcelPos: Position = { x: 1, y: 5 };
    const plan = makePlan([
      { action: 'move_up',    expectedPosition: { x: 0, y: 1 } },
      { action: 'pickup',     expectedPosition: parcelPos },  // parcel missing
    ]);
    const beliefs = mockBeliefs([], { x: 0, y: 0 }); // no parcels in beliefs
    const vr = validator.validate(plan, beliefs);

    assert.equal(vr.valid, false);
    assert.ok(vr.reason?.includes('no longer exists'), vr.reason);
    assert.ok(vr.reason?.includes(`(${parcelPos.x},${parcelPos.y})`), vr.reason);
  });

  it('fails when target parcel is carried by another agent', () => {
    const parcelPos: Position = { x: 0, y: 5 };
    const plan = makePlan([
      { action: 'pickup', expectedPosition: parcelPos },
    ]);
    // Parcel exists but is carried
    const beliefs = mockBeliefs(
      [makeParcel('p1', parcelPos, 'enemy')],
      parcelPos,
    );
    const vr = validator.validate(plan, beliefs);

    assert.equal(vr.valid, false);
    assert.ok(vr.reason?.includes('no longer exists'), vr.reason);
  });

  // -------------------------------------------------------------------------
  // (2) First move from wrong position
  // -------------------------------------------------------------------------

  it('fails when plan starts from wrong position', () => {
    // Agent at (4,4) but first step moves to (6,4) — 2 tiles right, not adjacent
    const plan = makePlan([
      { action: 'move_right', expectedPosition: { x: 6, y: 4 } },
    ]);
    const beliefs = mockBeliefs([], { x: 4, y: 4 });
    const vr = validator.validate(plan, beliefs);

    assert.equal(vr.valid, false);
    assert.ok(vr.reason?.includes('plan starts from wrong position'), vr.reason);
  });

  it('fails when agent is at wrong tile for first move (diagonal)', () => {
    // Agent at (4,4); step moves to (5,5) — diagonal, dist=2
    const plan = makePlan([
      { action: 'move_right', expectedPosition: { x: 5, y: 5 } },
    ]);
    const beliefs = mockBeliefs([], { x: 4, y: 4 });
    const vr = validator.validate(plan, beliefs);

    assert.equal(vr.valid, false);
    assert.ok(vr.reason?.includes('wrong position'), vr.reason);
  });

  it('accepts plan when first step is a pickup at current position (no initial move)', () => {
    const parcelPos: Position = { x: 4, y: 4 };
    const plan = makePlan([
      { action: 'pickup', expectedPosition: parcelPos },
      { action: 'move_down', expectedPosition: { x: 4, y: 3 } },
      // ... (we won't fully validate the route here)
    ]);
    const beliefs = mockBeliefs([makeParcel('p1', parcelPos)], parcelPos);
    const vr = validator.validate(plan, beliefs);
    assert.ok(vr.valid, vr.reason);
  });

  // -------------------------------------------------------------------------
  // (3) Move to non-walkable tile
  // -------------------------------------------------------------------------

  it('fails when a move step lands on a wall', () => {
    // (2,2) is a wall in the fixture map
    const plan = makePlan([
      { action: 'move_up',    expectedPosition: { x: 1, y: 1 } },
      { action: 'move_right', expectedPosition: { x: 2, y: 1 } },
      { action: 'move_up',    expectedPosition: { x: 2, y: 2 } }, // wall
    ]);
    const beliefs = mockBeliefs([], { x: 1, y: 0 });
    const vr = validator.validate(plan, beliefs);

    assert.equal(vr.valid, false);
    assert.ok(vr.reason?.includes('non-walkable'), vr.reason);
    assert.ok(vr.reason?.includes('2'), vr.reason); // step index or position
  });

  // -------------------------------------------------------------------------
  // (4) Pickup at wrong position
  // -------------------------------------------------------------------------

  it('fails when pickup step is not at agent current position', () => {
    const parcelPos: Position = { x: 0, y: 5 };
    const plan = makePlan([
      // Agent starts at (0,0); first pickup says (0,5) but we haven't moved there
      { action: 'pickup', expectedPosition: parcelPos },
    ]);
    // Agent is at (0,0), not (0,5)
    const beliefs = mockBeliefs([makeParcel('p1', parcelPos)], { x: 0, y: 0 });
    const vr = validator.validate(plan, beliefs);

    assert.equal(vr.valid, false);
    assert.ok(vr.reason?.includes('pickup at wrong position'), vr.reason);
  });

  // -------------------------------------------------------------------------
  // (5) Putdown at non-delivery zone
  // -------------------------------------------------------------------------

  it('fails when putdown is not at a delivery zone', () => {
    // (5,5) is walkable but not a delivery zone
    const plan = makePlan([
      { action: 'putdown', expectedPosition: { x: 5, y: 5 } },
    ]);
    const beliefs = mockBeliefs([], { x: 5, y: 5 });
    const vr = validator.validate(plan, beliefs);

    assert.equal(vr.valid, false);
    assert.ok(vr.reason?.includes('non-delivery-zone'), vr.reason);
  });

  it('accepts putdown at each fixture delivery zone', () => {
    for (const zone of FIXTURE_DELIVERY_ZONES) {
      const plan = makePlan([
        { action: 'putdown', expectedPosition: zone },
      ]);
      const beliefs = mockBeliefs([], zone);
      const vr = validator.validate(plan, beliefs);
      assert.ok(vr.valid, `delivery zone (${zone.x},${zone.y}) should be valid: ${vr.reason}`);
    }
  });

  // -------------------------------------------------------------------------
  // (BUG-4) Agent obstacle checking in move steps
  // -------------------------------------------------------------------------

  it('fails when a high-confidence agent blocks the first move destination', () => {
    // Agent at (5, 4) — the destination of the move step
    const dest: Position = { x: 5, y: 4 };
    const plan = makePlan([
      { action: 'move_right', expectedPosition: dest },
    ]);
    const beliefs = mockBeliefs([], { x: 4, y: 4 }, [makeAgent(dest, 1.0)]);
    const vr = validator.validate(plan, beliefs);

    assert.equal(vr.valid, false);
    assert.ok(vr.reason?.includes('agent-occupied'), vr.reason);
    assert.ok(vr.reason?.includes(`(${dest.x},${dest.y})`), vr.reason);
  });

  it('accepts plan when agent blocks a mid-route tile (step > 0): agents move during execution', () => {
    // Plan: move right to (5,4) then up to (5,5). Agent at (5,5) = step 1.
    // Mid-route agent blocking is NOT checked: agent may have moved before we get there.
    // Only the immediate first step is checked to prevent instant collisions.
    const agent: AgentBelief = makeAgent({ x: 5, y: 5 }, 0.9);
    const plan = makePlan([
      { action: 'move_right', expectedPosition: { x: 5, y: 4 } },
      { action: 'move_up',    expectedPosition: { x: 5, y: 5 } },
    ]);
    const beliefs = mockBeliefs([], { x: 4, y: 4 }, [agent]);
    const vr = validator.validate(plan, beliefs);

    // Mid-route agent should not cause rejection (only step 0 is checked)
    assert.ok(vr.valid, `mid-route agent must not reject: ${vr.reason}`);
  });

  it('accepts plan when agent confidence is too low (≤0.5)', () => {
    // Low-confidence agent at first move destination — should not block
    const dest: Position = { x: 5, y: 4 };
    const plan = makePlan([
      { action: 'move_right', expectedPosition: dest },
    ]);
    const beliefs = mockBeliefs([], { x: 4, y: 4 }, [makeAgent(dest, 0.4)]);
    const vr = validator.validate(plan, beliefs);

    assert.ok(vr.valid, `low-confidence agent should not block: ${vr.reason}`);
  });

  it('accepts plan when no agents are present', () => {
    const plan = makePlan([
      { action: 'move_right', expectedPosition: { x: 5, y: 4 } },
    ]);
    const beliefs = mockBeliefs([], { x: 4, y: 4 }, []);
    const vr = validator.validate(plan, beliefs);

    assert.ok(vr.valid, vr.reason);
  });
});
